### ISSUE TITLE
sendgmail go app should respect XDG

### ISSUE THREAD

**Issue by jasonkarns** [google/gmail-oauth2-tools#20]
Storing the json config in $HOME without respecting a user's configured XDG environment violates the spec.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by jasonkarns** [comment]
Ideally, the portion of the `.sendgmail.json` that is _not_ sensitive should be stored in `${XDG_CONFIG_HOME:-$HOME/.config}/sendgmail/config.json` and the client secret should be stored at `${XDG_DATA_HOME:-$HOME/.local/share}/sendgmail/config.json`.

However, to keep everything in one file, a minimal PR could just move the json file from `$HOME/.sendgmail.json` to `${XDG_DATA_HOME:-$HOME/.local/share}/.sendgmail.json`.

**Comment by junyer** [comment]
Now that I go looking for it, [`os.UserConfigDir()`](https://pkg.go.dev/os#UserConfigDir) is what I would use (and what I **_should_** have used), but the next question is how to introduce its use without breaking all of the existing users and without introducing complexity to handle "legacy" files in `$HOME`. Thoughts?

**Comment by jasonkarns** [comment]
Perhaps. Personally I don't think I'd ever expect mac users to go hunting in `$HOME/Library/Application Support`. MacOS is significantly *nix like that that I would consider that `os.UserConfigDir` package deficient in that regard. Further, most mac users that I know use some form of dotfiles versioning, and that is one of the primary benefits of XDG basedir. Moving the config files outside of XDG "just because darwin" removes that benefit from users that are most looking to use it. (That is _especially_ likely if `XDG_CONFIG_HOME` has been set explicitly, regardless of platform.)

**Comment by jasonkarns** [comment]
As far as a migration path, loads of tools have migrated a pretty consistent way. (git itself being a singular example)

Look for the files in the new location(s) first. If not found, fallback to the old locations.
If not found in either location and creating the files, use the new location.

This way existing files are respected with no change on the user's behalf. New installations use the new/preferred locations. Old installations that don't already have the files on disk are treated as new installations (writes to new location).

**Comment by junyer** [comment]
It might be simpler to use [build constraints](https://pkg.go.dev/cmd/go#hdr-Build_constraints) so that users who want XDG compliance can run, say, `go install -tags xdg …`.

**Comment by jasonkarns** [comment]
Easier for maintainers, perhaps, but not for users. This goes blatantly against the point of standards like XDG.

The entire point is to have a better default. If users have to opt-in at installation time, it's rather defeating the purpose.

**Comment by junyer** [comment]
I note that neither [AUR](https://aur.archlinux.org/packages/git-sendgmail-git) nor [Guix](https://packages.guix.gnu.org/packages/sendgmail/) patched sendgmail to comply with the XDG Base Directory Specification and, moreover, that no GitHub forks (let alone PRs) seem to have done so. I'm unwilling to solve a problem that apparently affects zero (0) users.

**Comment by favonia** [comment]
@junyer In case it helps, I'm one of the affected users. If you are fine with a PR, I can make one. I strongly believe @jasonkarns's suggestion is better.

**Comment by junyer** [comment]
Has something changed since January that renders the build constraint insufficient?

**Comment by favonia** [comment]
@junyer Well, I don't think anything has changed since January, but the current approach will prevent XDG from being widely adopted. The build constraint approach forces the choice _at the build time._ Thus, for backward compatibility, the package maintainers cannot possibly turn on the `xdg` tag, which means the XDG functionality will be disabled in most build scripts for `sendgmail`. The solution is to implement what @jasonkarns suggested: use XDG by default, and search for legacy files if XDG doesn't work.
