### ISSUE TITLE
Cannot generate token

### ISSUE THREAD

**Issue by alexDarcy** [google/gmail-oauth2-tools#21]
Hi, 
After an upgrade on my system today (Archlinux), I could not make offlineimap sync with gmail. I've tried to generate a new token and got a similar error : 

    λ python2 python/oauth2.py --generate_oauth2_token --client_id=XX=--client_secret=YY
    To authorize token, visit this url and follow the directions:
      https://accounts.google.com/o/oauth2/ZZZZ
    Enter verification code: WWWWW
    Traceback (most recent call last):
      File "python/oauth2.py", line 347, in <module>
        main(sys.argv)
      File "python/oauth2.py", line 326, in main
        authorization_code)
      File "python/oauth2.py", line 214, in AuthorizeTokens
        response = urllib.urlopen(request_url, urllib.urlencode(params)).read()
      File "/usr/lib/python2.7/socket.py", line 355, in read
        data = self._sock.recv(rbufsize)
      File "/usr/lib/python2.7/ssl.py", line 754, in recv
        return self.read(buflen)
      File "/usr/lib/python2.7/ssl.py", line 641, in read
        v = self._sslobj.read(len)
    ssl.SSLError: [SSL: KRB5_S_TKT_NYV] unexpected eof while reading (_ssl.c:1946)

Any advice ? Thanks

**Comment by trsdln** [comment]
@alexDarcy Hi, I've got the identical problem. Doesn't seem like this repo is maintained by anybody though.

After some digging I found out that it may be related to openssl version: http://marine.copernicus.eu/faq/what-are-the-motu-and-python-requirements/ (error identical). 

On my system both versions are installed:

```
pacman -Ss openssl                                                                                                                         
core/openssl 1.1.1.e-1 [installed]
core/openssl-1.0 1.0.2.u-1 [installed]
```
Unfortunately newest one is required by a lot of other important packages so removing it is not an option.

Right now I didn't found any easy solution to get python2 use older version of openssl. Playing around with `openssl` options didn't give any result for now:

```py
  sslcontext=ssl.create_default_context()
  sslcontext.options |= ssl.OP_NO_SSLv3

  response = urllib.urlopen(request_url, urllib.urlencode(params), context=sslcontext).read()
```
According to docs, newer openssl support was added relatively recently:

> Changed in version 2.7.13: Updated to support linking with OpenSSL 1.1.0

So, probably I will try to downgrade python2 as last resort. Also, rebuilding may be an option: https://stackoverflow.com/questions/5937337/building-python-with-ssl-support-in-non-standard-location.

Let me know if get any solution.

**Comment by alexDarcy** [comment]
The same issue has been reported to offlineimap : 
https://github.com/OfflineIMAP/offlineimap/issues/655

**Comment by JonnyMako** [comment]
rolling back openssl is risky and shouldn't be recommended. Who is the maintainer of this repo? Google?

**Comment by JonnyMako** [comment]
https://github.com/openssl/openssl/issues/11381

**Comment by JonnyMako** [comment]
OpenSSL EOF detection behavior is being reverted in 1.1.1, so I expect this to start working once that is released. However, the change to EOF detection is being kept on for OpenSSL release 3.0. This should give the maintainers of this application time to fix the issue before OpenSSL 3 is released. I suggest this issue not be closed until this API is fixed to work with the new EOF detection code.

https://github.com/openssl/openssl/pull/11400/commits/6611672ca5fe3aa97a50aa9092f190e07879ed8c

>Revert the change of EOF detection while reading in libssl to avoid
>regressions in applications depending on the current way of reporting
>the EOF. ***As the existing method is not fully accurate the change to
>reporting the EOF via SSL_ERROR_SSL is kept on the current development
>branch and will be present in the 3.0 release.***
>[Tomas Mraz]

[Emphasis mine]

**Comment by trsdln** [comment]
@JonnyMako Thanks. I will wait for 1.1.1f and then upgrade `openssl`.

**Comment by trsdln** [comment]
After upgrade to 1.1.1f issue is gone.

**Comment by alexDarcy** [comment]
I can confirm this, closing the issue.
