### ISSUE TITLE
Syntax errot

### ISSUE THREAD

**Issue by MiljanGitHub** [google/gmail-oauth2-tools#23]
I got my client_id and client_secret from google, and when I run in the console following command: 

python oauth2.py --client_id=##my_id --client_secret=##my_secret

 I got syntax error:
File "oauth2.py", line 297
    print 'Missing options: %s' % ' '.join(missing)
          ^
SyntaxError: invalid syntax

How to fix this?

**Comment by MiljanGitHub** [comment]
I fixed it

**Comment by angelapelletier** [comment]
How?

**Comment by tvartom** [comment]
To anyone landing here from Google.
You get that error if you run the script with python 3.
While waiting for Google to fix this, look at the pending Pull Requests or use python 2.
