### ISSUE TITLE
oauth2.py: Bad Request error, invalid grant

### ISSUE THREAD

**Issue by robertsawko** [google/gmail-oauth2-tools#29]
I've been using `oauth2.py` script for the last couple of months but this week it started tripping over. I have been able to debug it a little, but it seems the problem is with the server connection.

```bash
~/bin/oauth2.py \
    --user=abc@gmail.com \
    --client_id=*** \
    --client_secret=*** \
    --refresh_token=***
```

When I print `respone` variable I get:
```
{u'error_description': u'Bad Request', u'error': u'invalid_grant'}
```
I recreated the refresh token, but the problem remains. Please advise.

**Comment by Rodaxfck** [comment]
Same for me :( 

`HTTPError: HTTP Error 400: Bad Request`

**Comment by robertsawko** [comment]
Yes. I am going to close this, but I had the same fix and the same impression as you did, @Rodaxfck .
