### ISSUE TITLE
sendgmail: use the GMail API instead of SMTP

### ISSUE THREAD

**Issue by DemiMarie** [google/gmail-oauth2-tools#32]
This allows using a far more limited OAuth token.  sendgmail does not need the ability to delete email, for example.

This doesn’t matter on most systems, where sendgmail runs with the same privilege as the user’s browser.  However, it does matter for QubesOS users who want to use sendgmail from a different VM.

**Comment by ValZapod** [comment]
Also, I hope that will allow to hide localhost ip address, that is just shameful google, why do I need to reveal ipv6/v4 addresses to everyone, does not GMAIL API works the same way mail.google.com is working, i.e. no localhost info?

**Comment by junyer** [comment]
Once upon a time, sendgmail **_did_** use the Gmail API. However, I had to make it use SMTP instead because that was the only way to stop Gmail munging the plain text. Which is to say, if you want to mail patches, then you **_don't_** want to use the Gmail API. T_T

**Comment by ValZapod** [comment]
> then you **_don't_** want to use the Gmail API

Oogh. Well, you can just put a patch into txt and send it, it will be recognised by patchwork and mailer. See for example this: https://ffmpeg.org/pipermail/ffmpeg-devel/2021-June/281007.html

.patch will not be recognised.

> had to make it use SMTP instead

Okay, can you remove localhost ip somehow? See for example, 

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210531150302.359628-1-val.zapod.vz@gmail.com/ (download mbox file)

```
Received: from localhost ([2a00:1370:812d:8d4d:8d84:163e:25b3:1177])
 by smtp.gmail.com with ESMTPSA id d14sm1377775lfq.13.2021.05.31.08.03.01
 (version=TLS1_3 cipher=TLS_AES_128_GCM_SHA256 bits=128/128);
 Mon, 31 May 2021 08:03:01 -0700 (PDT)
```

This is my ipv6 address. Which as you should understand is white IP of the computer itself, there is no NAT. So any open ports are open into the Internet.

Also this cannot be real SMPT. Can it? Why do I publish oath2 content screen in Google Cloud then? It should be just a fake emulation, is not it. Oogh.

**Comment by DemiMarie** [comment]
> Once upon a time, sendgmail **_did_** use the Gmail API. However, I had to make it use SMTP instead because that was the only way to stop Gmail munging the plain text. Which is to say, if you want to mail patches, then you **_don't_** want to use the Gmail API. T_T

Did you try the multipart upload API?

**Comment by junyer** [comment]
> Did you try the multipart upload API?

That's not an option for Linux kernel patches, which is `sendgmail`'s _raison d'être_. See https://static.lwn.net/kerneldoc/process/submitting-patches.html#no-mime-no-links-no-compression-no-attachments-just-plain-text for more information.

**Comment by ValZapod** [comment]
>an option for Linux kernel patches, which are sendgmail's raison d'être.

Just plain text will still have DKIM signature and all required metadata. 

The way to go here is to fix Gmail API. LOL, it is 2021!

**Comment by DemiMarie** [comment]
> The way to go here is to fix Gmail API. LOL, it is 2022!

I mean how the heck can one report a bug in it to Google?

**Comment by favonia** [comment]
@junyer Sorry that I missed this conversation before making the PR #66. On the other hand, I have managed to use the patched `sendgmail` (together with `git`) to send patches to sourcehut and everything looks fine. (So, the arrival of sourcehut means Linux kernel is not the only usage.) Could you possibly point out how Gmail is messing up the plaintext emails? So far I have not seen it, but maybe I was lucky...

**Comment by junyer** [comment]
The original (internal) report from early April 2019 said:

> the patches are not correctly formatted; lines are wrapped and line terminators are being changed (\n -> \r\n).

The reporter attached full details of what they tried to send versus what actually ended up being sent. An illustrative snippet:

```
@@ -4620,7 +4624,6 @@ static void rt5677_gpio_config(struct rt5677_priv *rt5677, unsigned offset,
```

```
@@ -4620,7 +4624,6 @@ static void rt5677_gpio_config(struct
rt5677_priv *rt5677, unsigned offset,
```

Judging from both the discussion at the time and my notes, switching to SMTP was the only viable solution. If something has changed since then, I would be very keen to know what exactly, but I'm pessimistic that anything has changed in that regard.

**Comment by favonia** [comment]
@junyer Thanks. I tried sending fake emails with the same headers from `git` and many long lines (_way_ beyond 78 characters) and lots of spaces. Still didn't observe the hard line breaking or the replacement of line terminators. Could you (or someone in the internal report) possibly try it?

**Comment by junyer** [comment]
I asked Workspace DevRel to confirm that behaviour change and, if so, whether sendgmail can rely on said behaviour change for the foreseeable future.

**Comment by favonia** [comment]
@junyer I just rebased my previous code for your reference in case you get a positive response: https://github.com/favonia/fork4pr-gmail-oauth2-tools/tree/reduce-scope

**Comment by junyer** [comment]
Thanks. Unsurprisingly, it does resemble the code from ~4.5 years ago in terms of invoking the Gmail API. However, note that `git send-email` actually executes `sendmail -i`, not `sendmail -i -t`, so it doesn't specify `Bcc:` and instead specifies the recipients (`To:`, `Cc:`, `Bcc:`) on the command line. Thus, sendgmail needed to synthesise `Bcc:` explicitly for the Gmail API.

**Comment by favonia** [comment]
@junyer Done the `Bcc:` by a simple conversion of `flag.Args()`. An address will be added to `Bcc:` even if it's already in `To:`. I prefer not to parse the actual mail. :sweat_smile:

**Comment by junyer** [comment]
`mail.ReadMessage()` makes it straightforward to synthesise `Bcc:` precisely, so I would want to resurrect that logic, but let's not cross that bridge until we come to it.

**Comment by favonia** [comment]
@junyer Alright, then we will parse the mail when we come to it. I was trying minimize work. 😅 Parsing the mail will indeed approximate the bcc list better in many cases, but I don't see how we can reconstruct the list precisely when `git` is not helping us. More precisely, these two lines seem to generate the same arguments to `sendmail`:
```bash
git send-email --to=me@gmail.com
git send-email --to=me@gmail.com --bcc=me@gmail.com
```
I suppose you are referring to some "minimal" bcc list. I would argue that `Bcc:` _should_ include `me@gmail.com` in the second case but maybe it's better to exclude it if we cannot distinguish these two cases.

**Comment by junyer** [comment]
sendgmail would have exhibited the same behaviour, I suppose, because it used the `stringset` package to discard the `To:` and `Cc:` addresses from `flag.Args()` and then set `Bcc:` to the remaining addresses (if any). I agree that there's not much else that's feasible given the SMTP-like semantics (i.e. `RCPT TO` versus `DATA`) in play. So many aspects here are Not Ideal™.

**Comment by favonia** [comment]
@junyer I might have (finally!) encountered a case where Gmail inserted a newline. Strangely, the email looks perfect okay in Gmail itself and it looks correct if I download the original email from the Gmail web interface. However, the receiving end seems to get an email with an extra newline. So, maybe it's just that I have been very lucky so far. Sorry for the noise. 😟

**Comment by junyer** [comment]
No worries. I'm hoping that Workspace DevRel can offer some insights or even some hints, but this may indeed be infeasible.

**Comment by DemiMarie** [comment]
@junyer If it is infeasible, would that not mean that this is a bug in GMail?  Hopefully Workspace DevRel can get the backend code fixed.

**Comment by favonia** [comment]
My personal opinion is that maybe we should blame Git more for using a practically unreliable method. That is, `git send-email` should probably come up with a standardized way to **send patches as attachments using MIME.** No current email server will ever change any bit of an attached file, and thus we will have a reliable workflow. The reason I'm blaming Git more is that Git patches are very sensitive to even a change of a space character, so the format is arguably not "plain text". That is, it is very structured and is arguably closer to a special binary file that uses printable characters for markups. Even if someone manages to argue that it is "plain text", related RFCs arguably never emphasized that plain text should be kept intact _byte-to-byte_. In fact, many editors may re-wrap things as they wish, and you cannot really blame Gmail for re-wrapping things if you view the Gmail API as a way to "edit an email and send it as in the web interface" not a way to "send an email as it is directly". (You could blame Gmail for not using some cooler soft line breaks etc., but that's probably not a "bug".) Some email implementations happen to not touch "plain text" at all and thus meet `git send-email`'s high expectations, but I feel that is a big "if" on the entire email tool-chain. It's simply more reliable to use attachments, that is, to send the files generated by `git format-patch` as attachments.

**Comment by favonia** [comment]
@junyer If anything, maybe Gmail API can provide a "RawSend" method.

**Comment by junyer** [comment]
The Linux kernel development community is... [unequivocal](https://static.lwn.net/kerneldoc/process/submitting-patches.html#no-mime-no-links-no-compression-no-attachments-just-plain-text)... on the matter. ;)

FWIW, I honestly believe that the simplest thing that could possibly work here – and that would conveniently improve security across **_all_** non-API usage! – would be to support fine-grained OAuth2 scopes for IMAP, POP and SMTP. I just found [this](https://issuetracker.google.com/277134811) issue, BTW, and I can't say that I disagree with the sentiment expressed.

**Comment by paralin** [comment]
I am trying to send messages via the API: https://github.com/paralin/sendgmailapi

However recipients of the emails, sent with git send-email, are complaining that Gmail is wrapping the lines incorrectly: https://lore.kernel.org/buildroot/20240914110036.13d08b21@windsurf/T/

And indeed in that patch you can see Gmail has added newlines in the wrong places.

Was there any way around this other than using SMTP?

**Comment by rwuorinen81** [comment]
I need help... my wife passed away and I am trying to get important I
formation from her Gmail account I've tried messaging them and sending them
the death certificate and everything and they still will not give me access
even though I over see here estate. What can I do ?

**Comment by DemiMarie** [comment]
@paralin Did you try quoted-printable encoding and soft line breaks, as described at <https://stackoverflow.com/questions/40077884/gmail-api-plaintext-word-wrapping>?  That will solve the problem if the recipient’s email client properly decodes MIME, unless GMail has a bug on the backend.
