### ISSUE TITLE
GMail refresh token retrieval no longer working

### ISSUE THREAD

**Issue by mathstuf** [google/gmail-oauth2-tools#49]
Is this expected to work anymore? It seems that policies have changed and the `urn:ietf:wg:oauth:2.0:oob` URL is no longer valid. So…how is a desktop application supposed to communicate with the GMail API anymore?

**Comment by mathstuf** [comment]
It seems that using a `REDIRECT_URI = 'https://localhost'` is a workaround; the refresh token can be scraped from the address bar at least.

**Comment by mmackay055** [comment]
I had a similar issue when using the [oauth2.py](https://github.com/google/gmail-oauth2-tools/tree/master/python) but found it was using `https://accounts.google.com/o/oauth2/token` to request tokens vs using `https://oauth2.googleapis.com/token` as stated in google's documentation [docs](https://developers.google.com/identity/protocols/oauth2/native-app#exchange-authorization-code).

I feel there is probably other outdated urls in the script as well.

**Comment by fragtion** [comment]
Same problem here. Royally annoying changes to say the least. How can we best work around this?

**Comment by mathstuf** [comment]
See the second comment here for *a* workaround. I'll note that I got an email about OOB-using client IDs being expired in October, so I'll need this before then at least, but I'm not sure when I'll get to it..

**Comment by panamantis** [comment]
Yeah, I think my OOB is expired as well -- whatever that means.  So no option for python to refresh the token?

This gives a token that can be used for 1 hour which works...for 1 hour but...
https://support.datavirtuality.com/hc/en-us/community/posts/6854178746909-Migrate-Google-applications-from-using-the-deprecated-out-of-band-OOB-workflow

**Comment by junyer** [comment]
Fixed in commit 944cffd66df38863eb0252a8096961335e418e70.
