### ISSUE TITLE
oauth2.py uses outdated urls

### ISSUE THREAD

**Issue by mmackay055** [google/gmail-oauth2-tools#50]
When using [oauth2.py](https://github.com/google/gmail-oauth2-tools/tree/master/python) I kept getting authentication errors when submitting the code to retrieve a new token. I found it was using `https://accounts.google.com/o/oauth2/token` to request tokens vs using `https://oauth2.googleapis.com/token` as stated in [google's documentation](https://developers.google.com/identity/protocols/oauth2/native-app#exchange-authorization-code).

I feel there is probably other outdated urls in the script as well.

**Comment by junyer** [comment]
Sorry, I don't believe that the "old" endpoints have either been removed or been slated for removal, so I'm not sure what was causing the errors. It's conceivable that `oauth2.py` could switch to the "new" endpoints, but I suspect that this would entail a dependency on https://github.com/googleapis/google-api-python-client or similar, which I'm not keen to adopt at this time.
