### ISSUE TITLE
Python: SyntaxError: invalid syntax - Generate a Token

### ISSUE THREAD

**Issue by moitrierk** [google/gmail-oauth2-tools#56]
Hello,

I'm trying to generate a token with the oauth2 python script, but I have this error below : 
python oauth2.py 
  File "oauth2.py", line 34
    oauth2 --user=xxxxxx@gmail.com \
                             ^
SyntaxError: invalid syntax

I tried with python, python2, and python3.
With python 3 I have this error 👍 

File "oauth2.py", line 317
    print 'Access Token: %s' % response['access_token']

Thanks in advance for your help;

Best regards,

**Comment by junyer** [comment]
Fixed in commit 944cffd66df38863eb0252a8096961335e418e70.
