### ISSUE TITLE
How to Authenticator bypass or disable for google account

### ISSUE THREAD

**Issue by stijnkarel** [google/gmail-oauth2-tools#60]
I know the password of my gmail address. Any recovery code and recovery email address and recovery phone number are not registered. only authenticator and password protected. my phone malfunctioned, i had to do a soft reset. I didn't have an authenticator backup. so i can't login to my gmail account. my important documents were in my drive account. I need access. I wonder if there is a web app so I can bypass or disable gmail authenticator and only login with password? How can I recover? Can this be done with the app?

**Comment by junyer** [comment]
Sorry, this project can't help you with that.
